export const SIGNAL_REGISTRY_ABI = [
  {
    type: 'constructor',
    inputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'publishSignal',
    inputs: [
      { name: 'pair', type: 'string' },
      { name: 'basisPoints', type: 'int16' },
      { name: 'windowSeconds', type: 'uint256' },
      { name: 'priceAtCreation', type: 'uint256' },
    ],
    outputs: [{ name: 'signalId', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'settleSignal',
    inputs: [
      { name: 'signalId', type: 'uint256' },
      { name: 'correct', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'signals',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'agent', type: 'address' },
      { name: 'pair', type: 'string' },
      { name: 'basisPoints', type: 'int16' },
      { name: 'windowSeconds', type: 'uint256' },
      { name: 'stakedOKB', type: 'uint256' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'priceAtCreation', type: 'uint256' },
      { name: 'settled', type: 'bool' },
      { name: 'correct', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'reputation',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'signalCount',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'correctCount',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextSignalId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getReputations',
    inputs: [{ name: 'agents', type: 'address[]' }],
    outputs: [{ name: 'scores', type: 'int256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'SignalPublished',
    inputs: [
      { name: 'signalId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'pair', type: 'string', indexed: false },
      { name: 'basisPoints', type: 'int16', indexed: false },
      { name: 'windowSeconds', type: 'uint256', indexed: false },
      { name: 'stakedOKB', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SignalSettled',
    inputs: [
      { name: 'signalId', type: 'uint256', indexed: true },
      { name: 'agent', type: 'address', indexed: true },
      { name: 'correct', type: 'bool', indexed: false },
      { name: 'stakedOKB', type: 'uint256', indexed: false },
      { name: 'reputationDelta', type: 'int256', indexed: false },
    ],
  },
  {
    type: 'receive',
    stateMutability: 'payable',
  },
] as const;
